const { Users } = require('../models');

const usersData = [
  {
    first_name: 'Bob',
    last_name: 'Smith',
    email: 'bobsmith@tmail.com',
    password: 'Password1!',
    address:  '123 Main St',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
  },
  {
    first_name: 'Joe',
    last_name: 'Macky',
    email: 'joemacky@tmail.com',
    password: 'Password1!',
    address:  '123 Dick St',
    city: 'Fort Worth',
    state: 'TX',
    zipCode: '08569',
  },
  {
    first_name: 'Lily',
    last_name: 'Rodriguez',
    email: 'lilyrodriguez@tmail.com',
    password: 'Password1!',
    address:  '123 Poppy St',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '23040',
  },
  {
    first_name: 'Sally',
    last_name: 'Muntoe',
    email: 'sallymuntoe@tmail.com',
    password: 'Password1!',
    address:  '123 Barton St',
    city: 'Chicago',
    state: 'IL',
    zipCode: '48326',
  },
  {
    first_name: 'Mack',
    last_name: 'Buck',
    email: 'mackbuck@tmail.com',
    password: 'Password1!',
    address:  '123 Some st',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75201',
  },
  {
    first_name: 'Linda',
    last_name: 'Zimmerman',
    email: 'lindazimmerman@tmail.com',
    password: 'Password1!',
    address:  '123 South St',
    city: 'Orlando',
    state: 'FL',
    zipCode: '32801',
  },
  {
    first_name: 'Sue',
    last_name: 'Smith',
    email: 'suesmith@tmail.com',
    password: 'Password1!',
    address:  '123 Dallas St',
    city: 'miami',
    state: 'FL',
    zipCode: '33101',
  },
  {
    first_name: 'Mary',
    last_name: 'Jones',
    email: 'maryjones@tmail.com',
    password: 'Password1!',
    address:  '123 Main St',
    city: 'Brooklyn',
    state: 'NY',
    zipCode: '45678',
  },
];

const seedUsers = () => Users.bulkCreate(usersData);

module.exports = seedUsers;
